# Generated by Django 5.1 on 2024-08-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("comments", models.CharField(max_length=250)),
                ("link", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("added_by_suggestion", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("comments", models.CharField(max_length=250)),
                ("link", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("suggester", models.CharField(max_length=100)),
            ],
        ),
    ]
