# Generated by Django 5.1 on 2024-08-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorites",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
