# Generated by Django 5.0.7 on 2024-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_favorites_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestions",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
    ]
