# Generated by Django 5.0.7 on 2024-08-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_suggestions_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorites",
            options={"get_latest_by": "rank"},
        ),
        migrations.AlterModelTable(
            name="favorites",
            table="favorites",
        ),
    ]
