# Generated by Django 5.0.7 on 2024-09-03 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_alter_favorites_options_alter_favorites_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorites",
            options={},
        ),
        migrations.AddField(
            model_name="favorites",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="favorites",
            name="added_by_suggestion",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="comments",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="suggestions",
            name="comments",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="suggestions",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="suggestions",
            name="link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="suggestions",
            name="suggester",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name="suggestions",
            table="suggestions",
        ),
    ]
