# Generated by Django 5.0.7 on 2024-09-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suggestions",
            new_name="Recommendations",
        ),
        migrations.AlterModelTable(
            name="recommendations",
            table="recommendations",
        ),
    ]
